### PR TITLE
Move com_code com_trackerstatus and plg_content_nightlybuilds

### PR DESCRIPTION
**Pull request by zero-24**
add com_code com_trackerstatus and plg_content_nightlybuilds

Fixes https://github.com/joomla/joomla-websites/issues/864

### CODE REVIEW

**Comment by mbabker** [comment]
The components aren't here.

**Comment by zero-24** [comment]
@mbabker please doube check the git ignore files as i'm not 100% sure about them 😄

**Comment by mbabker** [comment]
Try using the one from https://github.com/joomla-projects/com_code/blob/master/.gitignore as the model and don't use .gitignore files in any of the subdirectories.

**Comment by zero-24** [comment]
Looks better now thanks @mbabker

**Comment by zero-24** [comment]
i have removed the other ones and just extened that one you linkend see: https://github.com/joomla/developer.joomla.org/pull/1/commits/c458eecdea84b65eb3f1541a9bbfbc8ba7857581

**Comment by zero-24** [comment]
Thanks @mbabker

**Pull request merged**
