### PR TITLE
2FA image fix

### PR DESCRIPTION
**Pull request by conconnl**
The 2FA image on edit profile wasn't visible because of CSP

### CODE REVIEW

**Comment by zero-24** [comment]
Can you say what domain you had to add? IIRC that 2fa stuff should be local since a few releases?

**Comment by conconnl** [comment]
No domain....
img-src data:

**Comment by conconnl** [comment]
image

The fix was even need to make 2FA work.

**Comment by zero-24** [comment]
Ok 👍 from me.

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
